name: Build books

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Install pandoc, xelatex, latex"
        run: |
          sudo apt-get update
          sudo apt-get install pandoc texlive-base texlive-latex-base texlive-xetex texlive-latex-recommended  texlive-fonts-extra
      - name: Chackout
        uses: actions/checkout@v4
      - name: Move template
        run: mkdir -p ~/.pandoc/templates; cp eisvogel.latex ~/.pandoc/templates
      - name: Build pdf
        run: sudo chmod +x pdf.sh && sudo ./pdf.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xBRL-Quickguide.pdf
          path: xbrl-quickguide.pdf
      - name: "Create Release"
        uses: softprops/action-gh-release@v2.5.0
        with:
          files: xbrl-quickguide.pdf
          draft: false
          body: "Update after merge"
          generate_release_notes: true


